dist: trusty
language: node_js

node_js:
  - '6.10'

before_script:
  - npm install

script:
  - sleep 5
  - npm test

addons:
  sauce_connect:
    username: "fabionit"
    access_key: "ce71f4ac-f67a-4a0e-9183-6a14205535bf"