dist: trusty
language: node_js

node_js:
  - '6.10'

before_script:
- wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
- unzip BrowserStackLocal-linux-x64.zip
- ./BrowserStackLocal -v -onlyAutomate -forcelocal $BROWSERSTACK_ACCESS_KEY &
- sleep 3
- npm install

script:
  - sleep 5
  - npm test

browserName: 'chrome',
project: 'myApp',
version: '59.0',
build: 'myApp #' + process.env.TRAVIS_BUILD_NUMBER + '.' + process.env.TRAVIS_JOB_NUMBER,
'browserstack.local': 'true',
'browserstack.debug': 'true'